config/routes.rb
Cookery::Application.routes.draw do
  get "recepes/pic"
  post "recepes/index"

  resources :recepes
  

end

app/models/recepe.rb
class Recepe < ActiveRecord::Base
	belongs_to :type
	attr_accessible :id, :type_id, :name, :description, :ingredients, :content_type, :picture, :uploaded_picture
	validates_presence_of :name


	def uploaded_picture=(picture_field)
		self.content_type = picture_field.content_type.chomp
		self.picture = picture_field.read
	end

	def pic
		return self.picture, type: self.content_type, disposition: "inline"
	end
end

app/models/type.rb
class Type < ActiveRecord::Base
	has_one :recepe
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/recepes_controller.rb
class RecepesController < ApplicationController
  # GET /recepes
  # GET /recepes.json
  before_filter :set_types

  def index
    if params[:search]
      @recepes = Recepe.where("name like '%#{params[:search]}%'")
    elsif params[:type_id]
      @recepes = Recepe.where("type_id = '#{params[:type_id]}'")
    else
      @recepes = Recepe.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recepes }  
    end
  end

  # GET /recepes/1
  # GET /recepes/1.json
  def show
    @recepe = Recepe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recepe }
      format.xml { render xml: @recepe }

    end
  end

  # GET /recepes/new
  # GET /recepes/new.json
  def new
    @recepe = Recepe.new

   @types = Type.all
  
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recepe }
    end
  end

  # GET /recepes/1/edit
  def edit
    @recepe = Recepe.find(params[:id])
  end

  # POST /recepes
  # POST /recepes.json
  def create
    @recepe = Recepe.new(params[:recepe])

    respond_to do |format|
      if @recepe.save
        format.html { redirect_to @recepe, notice: 'Recepe was successfully created.' }
        format.json { render json: @recepe, status: :created, location: @recepe }
      else
        format.html { render action: "new" }
        format.json { render json: @recepe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recepes/1
  # PUT /recepes/1.json
  def update
    @recepe = Recepe.find(params[:id])

    respond_to do |format|
      if @recepe.update_attributes(params[:recepe])
        format.html { redirect_to @recepe, notice: 'Recepe was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @recepe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recepes/1
  # DELETE /recepes/1.json
  def destroy
    @recepe = Recepe.find(params[:id])
    @recepe.destroy

    respond_to do |format|
      format.html { redirect_to recepes_url }
      format.json { head :ok }
      format.js
    end
  end

  def pic
    @picture = Recepe.find(params[:id])
    send_data(@picture.picture, type: @picture.content_type, disposition: "inline")
  end

  def set_types
    @types = Type.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recepes_helper.rb
module RecepesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Моя кулинарная книга</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= form_tag do %>
		<div class="search" id="search">Поиск: <%= search_field_tag :search %>
		<%= submit_tag 'Искать', class:"search_button"%></div>
	<% end %>

	<header>Моя кулинарная книга</header>
	<aside>
		<nav>
			<ul>
				<li><%= link_to "На главную", recepes_path %></li>
				<li><a href="#" id="li_search">Поиск по рецептам</a><div id="search_form">Выберите раздел<br/><%= select_tag :type_id, options_from_collection_for_select(@types, "id", "name"), include_blank: "--Все--" %><br/><br/></div></li>
				<li><a href="#">Контакты</a></li>
				<li><a href="#">Регистрация</a></li>
				<li><a href="#">Войти</a></li>
			</ul>
		</nav>
	</aside>
	
	<main>
		<%= yield %>
	</main>

	<footer>
		<small>2014 © Быкова Виктория</small>
	</footer>

	</body>
</html>

app/views/recepes/_form.html.erb
<%= form_for(@recepe, html: {multipart: true}) do |f| %>
  <% if @recepe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recepe.errors.count, "error") %> prohibited this recepe from being saved:</h2>

      <ul>
      <% @recepe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :Название %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :Тип %><br />
    <%= f.select :type_id, Type.all.collect {|c| [ c.name, c.id ]},{}%>
  </div>
  <div class="field">
    <%= f.label :Описание %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :Ингредиенты %><br />
    <%= f.text_area :ingredients %>
  </div>
  <div class="field">
    <%= f.label :Фотография %><br />
    <%= f.file_field("uploaded_picture") %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recepes/_recepe.html.erb
<% i = 0 %>
<% if i % 2 == 0 %>
	      	<tr>
<% end %>
	<td class="meal" id="recepe_<%=recepe.id%>"><%= recepe.name %><br/><img src="<%= url_for(action: :pic, id: recepe.id) %>"/></td>
	<td><%= sanitize(recepe.ingredients) %><br/>
	<td>
		<%= link_to 'Показать', recepe %>
		<%= link_to 'Редактировать', edit_recepe_path(recepe) %>
		<%= link_to 'Удалить', recepe, confirm: 'Вы уверены?', method: :delete, remote: true %></td>
	</td>
<% if i % 2 != 0 %>
	 		</tr>
<% end %>
<% i+=1 %>

app/views/recepes/destroy.js.erb
$('#<%= dom_id(@recepe) %>').next().fadeOut();
$('#<%= dom_id(@recepe) %>').fadeOut();

app/views/recepes/edit.html.erb
<h1>Редактирование рецепта</h1>

<%= render 'form' %>

<%= link_to 'Показать', @recepe %> |
<%= link_to 'Обратно', recepes_path %>

app/views/recepes/index.html.erb
<h1>Просмотр рецептов</h1>
<div id="new"><%= link_to 'Добавить рецепт', new_recepe_path %></div>

<table>
	<%= render @recepes %>
</table>


<br />

app/views/recepes/index.js.erb
alert('render');
$('table').html("<%=j render @recepes %>");

app/views/recepes/new.html.erb
<h1>Новый рецепт</h1>

<%= render 'form' %>

<%= link_to 'Назад', recepes_path %>

app/views/recepes/show.html.erb
<p id="notice"><%= notice %></p>


<p class="meal">
   <img src="<%= url_for(action: :pic, id: @recepe.id) %>"/>
</p>
<p>
  <b>Название:</b>
  <%= @recepe.name %>
</p>


<p>
  <b>Описание:</b>
  <%= @recepe.description %>
</p>

<p>
  <b>Ингредиенты:</b>
  <%= @recepe.ingredients %>
</p>


<%= link_to 'Edit', edit_recepe_path(@recepe) %> |
<%= link_to 'Back', recepes_path %>